### ISSUE TITLE
yacd管理页面问题

### ISSUE THREAD

**Issue by SmartYou1995** [zusterben/plan_c#11]
yacd管理页面无法正确进入显示如图
![Uploading 屏幕截图 2024-09-08 082340.png…]()

**Comment by SmartYou1995** [comment]
![Uploading 屏幕截图 2024-09-08 082340.png…]()

**Comment by SmartYou1995** [comment]
![屏幕截图 2024-09-08 082340](https://github.com/user-attachments/assets/205d4b76-ba0c-4874-a9c6-259f30853945)

**Comment by zusterben** [comment]
你浏览器问题
