### ISSUE TITLE
离线安装失败，路径错误

### ISSUE THREAD

**Issue by wujin941005** [zusterben/plan_c#6]
```
2020年08月11日 03:02:25】: ====================== step 1 ===========================
【2020年08月11日 03:02:25】: 开启软件离线安装！
【2020年08月11日 03:02:25】: /tmp/upload目录下检测到上传的离线安装包merlinclash.tar.gz，大小：11.3M
【2020年08月11日 03:02:25】: 尝试解压离线安装包离线安装包
【2020年08月11日 03:02:26】: 解压完成！
【2020年08月11日 03:02:26】: 准备安装merlinclash插件！
【2020年08月11日 03:02:26】: 找到安装脚本！
【2020年08月11日 03:02:26】: 运行安装脚本...
【2020年08月11日 03:02:26】: ====================== step 2 ===========================
/tmp/merlinclash/install.sh: source: line 3: can't open '/jffs/softcenter/scripts/base.sh'
【2020年08月11日 03:02:27】: 因为merlinclash插件安装失败！退出离线安装！
【2020年08月11日 03:02:27】: ======================== end ============================
```

我的AC86U Merlin改版不存在/jffs/softcenter这个路径，软件中心版本1.6.1，正确的路径应该是`/jffs/.koolshare/scripts`吧？

**Comment by zyh2137830** [comment]
我也是AC86U 跟你的路径是一样的

**Comment by yflwz** [comment]
我的是K3，刷380.70_0_X7.9.1，下载arm的包离线安装提示
【2020年10月15日 23:29:24】: ====================== step 1 ===========================
【2020年10月15日 23:29:24】: 开启软件离线安装！
【2020年10月15日 23:29:24】: /tmp目录下检测到上传的离线安装包merlinclash.tar.gz，大小：11.4M
【2020年10月15日 23:29:24】: 尝试解压离线安装包离线安装包
【2020年10月15日 23:29:26】: 解压完成！
【2020年10月15日 23:29:26】: 准备安装merlinclash插件！
【2020年10月15日 23:29:26】: 找到安装脚本！
【2020年10月15日 23:29:26】: 运行安装脚本...
【2020年10月15日 23:29:26】: ====================== step 2 ===========================
/tmp/merlinclash/install.sh: source: line 3: can't open '/jffs/softcenter/scripts/base.sh'
【2020年10月15日 23:29:27】: 因为merlinclash插件安装失败！退出离线安装！
【2020年10月15日 23:29:27】: ======================== end ============================
 
XU6J03M6

**Comment by yflwz** [comment]
把install.sh和uninstall.sh文件中所有的softcenter替换成.koolshare后，重新打包上传安装成功。
【2020年10月15日 23:47:37】: ====================== step 1 ===========================
【2020年10月15日 23:47:37】: 开启软件离线安装！
【2020年10月15日 23:47:37】: /tmp目录下检测到上传的离线安装包merlinclash.tar.gz，大小：11.2M
【2020年10月15日 23:47:37】: 尝试解压离线安装包离线安装包
【2020年10月15日 23:47:38】: 解压完成！
【2020年10月15日 23:47:38】: 准备安装merlinclash插件！
【2020年10月15日 23:47:38】: 找到安装脚本！
【2020年10月15日 23:47:38】: 运行安装脚本...
【2020年10月15日 23:47:38】: ====================== step 2 ===========================
【2020年10月15日 23:47:39】: 检测jffs分区剩余空间...
【2020年10月15日 23:47:39】: U盘已挂载，继续安装！
【2020年10月15日 23:47:39】: 清理旧文件,保留已上传配置文件
【2020年10月15日 23:47:39】: 开始复制文件！
【2020年10月15日 23:47:39】: 复制相关二进制文件！此步时间可能较长！
【2020年10月15日 23:47:45】: 复制相关的脚本文件！
【2020年10月15日 23:47:45】: 复制相关的网页文件！
【2020年10月15日 23:47:45】: 为新安装文件赋予执行权限...
【2020年10月15日 23:47:45】: 创建一些二进制文件的软链接！
【2020年10月15日 23:47:45】: 一点点清理工作...
【2020年10月15日 23:47:45】: clash插件安装成功！
【2020年10月15日 23:47:45】: 创建yaml文件列表
【2020年10月15日 23:47:45】: 初始化配置文件处理完成
【2020年10月15日 23:47:45】: 更新完毕，请等待网页自动刷新！
【2020年10月15日 23:47:45】: ====================== step 3 ===========================
【2020年10月15日 23:47:45】: 插件安装脚本里没有找到版本号，设置默认版本号为0.1
【2020年10月15日 23:47:45】: 离线包安装完成！
【2020年10月15日 23:47:45】: 一点点清理工作...
【2020年10月15日 23:47:45】: 完成！离线安装插件成功，现在你可以退出本页面~
【2020年10月15日 23:47:45】: ======================== end ============================

**Comment by yflwz** [comment]
晕，安装成功后，clash是有了，但是除了开关有反应之外，按其他任意功能都没有反应。

**Comment by wujin941005** [comment]
> 晕，安装成功后，clash是有了，但是除了开关有反应之外，按其他任意功能都没有反应。

用这个吧
https://t.me/merlinclashcat
